kind: Route
apiVersion: route.openshift.io/v1
metadata:
# set your user name
  name:  {{ .Release.Name }}-route
  annotations:
    haproxy.router.openshift.io/disable_cookies: 'True'
spec:
  to:
    kind: Service
# set your user name
    name:  {{ .Release.Name }}-service
    weight: 100
  port:
    targetPort: {{ .Values.service.servicePort }}
  wildcardPolicy: None