kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blue-green-route
  annotations:
    haproxy.router.openshift.io/disable_cookies: 'true'
    haproxy.router.openshift.io/balance: 'roundrobin'
spec:
  to:
    kind: Service
    name: maor-hello-world
    weight: 100
  alternateBackends:
  - kind: Service
    name: user8-hello-world-service
    weight: 0
