ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/maor_ben_shoeff/redhat'
  tag: 'v3'

service:
  servicePort: 8080

probes:
  readiness:
    path: '/health/readiness'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    path: '/health/liveliness'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

volume:
  mount:
    path: '/tmp/html'

test: 'Healty'

github:
  user: 'maorbs'
  token: ''
  url: 'https://api.github.com/repos/maorbs/Redhat/issues'